# Google Cloud Run service configuration
# This file provides deployment configuration examples
# Deploy using: gcloud run deploy --source .

# Example deployment command:
# gcloud run deploy camOS-analytics \
#   --source . \
#   --region us-central1 \
#   --port 8080 \
#   --allow-unauthenticated \
#   --memory 1Gi \
#   --cpu 1 \
#   --max-instances 10

# Optional environment variables to set during deployment:
# NODE_ENV=production
# CLOUD_RUN_SERVICE_URL=https://your-service-url.run.app
# PRODUCTION_DOMAIN=your-custom-domain.com (if using custom domain)