"""Ten-table contract on disposable localhost PG. No production DDL/migrations."""

from backend.tests.membership_postgres import LocalPostgres

SCHEMA = r"""
DROP TABLE public.sites;
CREATE TABLE public.sites (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL,
 organisation_id bigint NOT NULL REFERENCES public.organisations(id) ON DELETE RESTRICT,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 max_capacity smallint NOT NULL, enabled boolean NOT NULL DEFAULT true, UNIQUE(organisation_id,name)
);
CREATE TABLE public.devices (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL,
 site_id bigint NOT NULL REFERENCES public.sites(id) ON DELETE RESTRICT, enabled boolean NOT NULL DEFAULT true,
 analysis_interval_minutes integer NOT NULL CHECK(analysis_interval_minutes>0), analyzed_until timestamptz,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 last_connected_at timestamptz, last_frame_seen_at timestamptz, last_frame_uploaded_at timestamptz, rtsp_uri text,
 rtsp_username text NOT NULL DEFAULT '', rtsp_password text NOT NULL DEFAULT '', capture_fps smallint NOT NULL DEFAULT 3,
 change_threshold_bp smallint NOT NULL DEFAULT 50, line_ax smallint, line_ay smallint, line_bx smallint, line_by smallint,
 frame_package_interval_minutes integer NOT NULL DEFAULT 15 CHECK(frame_package_interval_minutes>0), UNIQUE(site_id,name)
);
CREATE TABLE public.gateways (
 gateway_id uuid PRIMARY KEY, site_id bigint UNIQUE REFERENCES public.sites(id) ON DELETE RESTRICT,
 desired_state smallint NOT NULL DEFAULT 1 CHECK(desired_state IN(0,1,2)), restart_requested_at timestamptz,
 last_seen_at timestamptz, commission_hash bytea, desired_version text NOT NULL DEFAULT '1.0' CHECK(desired_version<>''),
 reported_version text CHECK(reported_version IS NULL OR reported_version<>'')
);
CREATE UNIQUE INDEX gateways_commission_hash_unique ON public.gateways(commission_hash) WHERE commission_hash IS NOT NULL;
CREATE TABLE public.organisation_snapshots (
 organisation_id bigint PRIMARY KEY REFERENCES public.organisations(id), ts timestamptz NOT NULL,
 payload jsonb NOT NULL, state jsonb NOT NULL, updated_at timestamptz NOT NULL
);
CREATE TABLE public.site_snapshots (
 site_id bigint PRIMARY KEY REFERENCES public.sites(id), ts timestamptz NOT NULL,
 payload jsonb NOT NULL, state jsonb NOT NULL, updated_at timestamptz NOT NULL
);
CREATE TABLE public.alarms (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organisation_id bigint NOT NULL REFERENCES public.organisations(id),
 site_id bigint NOT NULL REFERENCES public.sites(id), device_id bigint REFERENCES public.devices(id), gateway_id uuid REFERENCES public.gateways(gateway_id),
 alarm_type text NOT NULL, severity text NOT NULL CHECK(severity IN('low','medium','high')), started_at timestamptz NOT NULL,
 cleared_at timestamptz CHECK(cleared_at IS NULL OR cleared_at>=started_at), CHECK((device_id IS NOT NULL)<>(gateway_id IS NOT NULL))
);
"""


def database():
    db = LocalPostgres()
    db.migrate()
    db.query(SCHEMA)
    return db
