-- Administrator only. Review production schema first; never run at app startup.
-- psql -v ON_ERROR_STOP=1 -f backend/migrations/002_canonical_user_lifecycle.sql
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';
LOCK TABLE public.users IN ACCESS EXCLUSIVE MODE;

-- Existing users.id is bigint without a default. Refuse unexpected generation
-- rather than overwriting a production sequence. Preserve every existing ID.
DO $migration$
DECLARE generation text; existing_default text; highest bigint;
BEGIN
    SELECT is_identity, column_default INTO STRICT generation, existing_default
      FROM information_schema.columns
      WHERE table_schema='public' AND table_name='users' AND column_name='id'
        AND data_type='bigint';
    IF generation <> 'NO' OR existing_default IS NOT NULL THEN
        RAISE EXCEPTION 'users.id already has generation; inspect before applying migration';
    END IF;
    ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    SELECT max(id) INTO highest FROM public.users;
    IF highest IS NOT NULL AND highest >= 1 THEN
        PERFORM setval(pg_get_serial_sequence('public.users','id'), highest, true);
    END IF;
END
$migration$;

-- Canonical lookup already assumes case-insensitive unique identifiers.
CREATE UNIQUE INDEX IF NOT EXISTS users_email_ci ON public.users(lower(email));
CREATE UNIQUE INDEX IF NOT EXISTS users_username_ci ON public.users(lower(username));
-- A pre-existing same-named index must actually enforce the expected invariant.
DO $indexes$
DECLARE item record;
BEGIN
    FOR item IN SELECT * FROM (VALUES ('users_email_ci', 'lower(email)'),
                                     ('users_username_ci', 'lower(username)')) AS expected(name, expression)
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM pg_index i JOIN pg_class c ON c.oid = i.indexrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = 'public' AND c.relname = item.name
              AND i.indrelid = 'public.users'::regclass AND i.indisunique
              AND i.indisvalid AND i.indpred IS NULL AND i.indnkeyatts = 1
              AND pg_get_indexdef(i.indexrelid, 1, true) = item.expression
        ) THEN
            RAISE EXCEPTION 'Unexpected identifier index %; inspect before applying migration', item.name;
        END IF;
    END LOOP;
END
$indexes$;
ALTER TABLE public.users ADD COLUMN session_version bigint NOT NULL DEFAULT 0
    CHECK (session_version >= 0);
ALTER TABLE public.users ADD COLUMN account_version bigint NOT NULL DEFAULT 0
    CHECK (account_version >= 0);

-- Documents historically use username as accountId. Keep that namespace
-- immutable; new users get a separate random canonical key. No blob moves.
ALTER TABLE public.users ADD COLUMN document_owner_key text;
UPDATE public.users SET document_owner_key = username;
ALTER TABLE public.users ALTER COLUMN document_owner_key SET NOT NULL;
CREATE UNIQUE INDEX users_document_owner_key ON public.users(document_owner_key);

CREATE TABLE public.user_lifecycle_challenges (
    id text PRIMARY KEY,
    purpose text NOT NULL CHECK (purpose IN ('signup','reset','unlock')),
    email text NOT NULL,
    user_id bigint REFERENCES public.users(id),
    session_version bigint,
    session_binding text,
    payload jsonb NOT NULL DEFAULT '{}',
    code_hash text NOT NULL,
    code_expires_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 5),
    resends integer NOT NULL DEFAULT 0 CHECK (resends BETWEEN 0 AND 5),
    last_sent_at timestamptz NOT NULL,
    state text NOT NULL DEFAULT 'pending'
        CHECK (state IN ('pending','granted','consumed','exhausted')),
    grant_hash text,
    grant_expires_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (code_expires_at <= expires_at),
    CHECK (purpose = 'signup' OR (user_id IS NOT NULL AND session_version IS NOT NULL)),
    CHECK (purpose <> 'unlock' OR session_binding IS NOT NULL)
);
CREATE INDEX user_lifecycle_user ON public.user_lifecycle_challenges(user_id, purpose);
CREATE INDEX user_lifecycle_expiry ON public.user_lifecycle_challenges(expires_at);

-- Shared fixed-hour budgets survive restarting challenges and span instances.
-- Keys are HMACs, not IP addresses or raw email addresses.
CREATE TABLE public.user_lifecycle_limits (
    key text PRIMARY KEY,
    window_started_at timestamptz NOT NULL,
    count integer NOT NULL CHECK (count > 0)
);
COMMIT;
