-- Administrator-only source for future environments. Live changes are already applied.
-- Never executed by application startup; do not apply to production for this correction.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';
LOCK TABLE public.users IN ACCESS EXCLUSIVE MODE;

DO $identity$
DECLARE generation text; identity_kind text; existing_default text;
        highest bigint; sequence_highest bigint;
BEGIN
    SELECT is_identity, identity_generation, column_default
      INTO STRICT generation, identity_kind, existing_default
      FROM information_schema.columns
      WHERE table_schema='public' AND table_name='users' AND column_name='id'
        AND data_type='bigint';
    IF generation = 'NO' AND existing_default IS NULL THEN
        ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    ELSIF generation <> 'YES' OR identity_kind <> 'BY DEFAULT' THEN
        RAISE EXCEPTION 'Unexpected users.id generation; inspect before migration';
    END IF;
    IF pg_get_serial_sequence('public.users','id') <> 'public.users_id_seq' THEN
        RAISE EXCEPTION 'Unexpected users identity sequence';
    END IF;
    SELECT max(id) INTO highest FROM public.users;
    SELECT last_value INTO sequence_highest FROM public.users_id_seq;
    IF highest IS NOT NULL AND highest >= 1 AND highest >= sequence_highest THEN
        PERFORM setval('public.users_id_seq', highest, true);
    END IF;
END
$identity$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email_ci ON public.users(lower(email));
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_username_ci ON public.users(lower(username));
DO $indexes$
DECLARE item record;
BEGIN
    FOR item IN SELECT * FROM (VALUES ('uq_users_email_ci', 'lower(email)'),
                                     ('uq_users_username_ci', 'lower(username)')) AS expected(name, expression)
    LOOP
        IF NOT EXISTS (
            SELECT 1 FROM pg_index i JOIN pg_class c ON c.oid = i.indexrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE n.nspname = 'public' AND c.relname = item.name
              AND i.indrelid = 'public.users'::regclass AND i.indisunique
              AND i.indisvalid AND i.indpred IS NULL AND i.indnkeyatts = 1
              AND pg_get_indexdef(i.indexrelid, 1, true) = item.expression
        ) THEN
            RAISE EXCEPTION 'Unexpected identifier index %', item.name;
        END IF;
    END LOOP;
END
$indexes$;

-- created_at has NO default; signup explicitly supplies CURRENT_TIMESTAMP.
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS session_version bigint NOT NULL DEFAULT 0
    CHECK (session_version >= 0);

CREATE TABLE IF NOT EXISTS public.user_lifecycle_challenges (
    id text PRIMARY KEY,
    purpose smallint NOT NULL CHECK (purpose IN (0,1,2)),
    user_id bigint NULL REFERENCES public.users(id),
    payload jsonb NOT NULL DEFAULT '{}',
    code_hash text NOT NULL,
    code_expires_at timestamptz NOT NULL,
    attempts smallint NOT NULL DEFAULT 0,
    resends smallint NOT NULL DEFAULT 0,
    last_sent_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified_at timestamptz NULL,
    consumed_at timestamptz NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
