import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { readFile, mkdir } from 'node:fs/promises';
import { chromium } from 'playwright';
import { expect } from '@playwright/test';
const base=process.env.PORTAL_BROWSER_BASE_URL??'http://127.0.0.1:3000';
const runtime=spawn(process.env.PORTAL_TEST_PYTHON??'python',['-m','backend.tests.run_documents_browser'],{cwd:'..',env:process.env,stdio:['ignore','pipe','pipe']});
let log='';runtime.stdout.on('data',data=>log+=data);runtime.stderr.on('data',data=>log+=data);
let browser;const errors=[];const output='test-results/documents';
const arrange=async(page,body)=>assert.equal((await page.request.post('http://127.0.0.1:8000/__test/documents',{data:body})).status(),200);
const signIn=async(page,id)=>{
 await page.goto(base+'/login',{waitUntil:'domcontentloaded'});
 await page.getByLabel('Email or username').fill('documents-user'+id);
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByLabel('Password',{exact:true}).fill('documents-browser-password');
 await page.getByRole('button',{name:'Login',exact:true}).click();await expect(page).toHaveURL(/\/home$/);
};
try{
 await expect.poll(async()=>{if(runtime.exitCode!==null)throw Error(log);try{return(await fetch('http://127.0.0.1:8000/api/me')).status;}catch{return 0;}},{timeout:20000}).toBe(401);
 browser=await chromium.launch({headless:true,...(process.env.PORTAL_BROWSER_EXECUTABLE?{executablePath:process.env.PORTAL_BROWSER_EXECUTABLE}:{})});
 await mkdir(output,{recursive:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
 let page=await context.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://consent.cookiebot.com/**',r=>r.abort());
 let catalogueRequests=0;page.on('request',r=>{if(new URL(r.url()).pathname==='/api/documents')catalogueRequests++;});
 await signIn(page,0);assert.equal(catalogueRequests,0,'Login must not list Documents');
 await page.route('**/api/documents',async r=>{await new Promise(resolve=>setTimeout(resolve,250));await r.continue();});
 await page.goto(base+'/documents',{waitUntil:'domcontentloaded'});
 await expect(page.getByText('Loading documents...', {exact:true})).toBeVisible();
 await expect(page.getByRole('heading',{name:'No documents yet'})).toBeVisible();
 await page.screenshot({path:output+'/empty-desktop.png',fullPage:true});
 await arrange(page,{action:'add',name:'0/0test.csv',content:'one,two\n'});
 await arrange(page,{action:'add',name:'0/nested/ignored.csv'});
 await arrange(page,{action:'add',name:'1/private.csv'});
 await page.getByRole('button',{name:'Refresh',exact:true}).click();
 await expect(page.getByRole('heading',{name:'0test.csv',exact:true})).toBeVisible();
 await expect(page.getByText('private.csv',{exact:true})).toHaveCount(0);
 await expect(page.getByText('ignored.csv',{exact:true})).toHaveCount(0);
 // A real authenticated download: no public URL or browser-selected prefix.
 const downloadPromise=page.waitForEvent('download');
 await page.getByRole('button',{name:'Download 0test.csv',exact:true}).click();
 const download=await downloadPromise;assert.equal(download.suggestedFilename(),'0test.csv');
 assert.equal((await readFile(await download.path())).toString(),'one,two\n');
 let uploadButton=page.getByRole('button',{name:'Upload document',exact:true});await uploadButton.click();
 let dialog=page.getByRole('dialog',{name:'Upload documents'});
 await expect(dialog.getByRole('button',{name:'Close upload modal'})).toBeFocused();
 await page.keyboard.press('Shift+Tab');await expect(dialog.getByRole('button',{name:'Cancel',exact:true})).toBeFocused();
 await dialog.locator('input[type=file]').setInputFiles([{name:'new.csv',mimeType:'text/csv',buffer:Buffer.from('uploaded')},{name:'0test.csv',mimeType:'text/csv',buffer:Buffer.from('must not overwrite')}]);
 await dialog.getByRole('button',{name:'Upload',exact:true}).click();
 await expect(dialog.getByRole('alert')).toContainText('Some files failed');
 await expect(dialog.getByText('A document with this filename already exists. Rename the file and try again.',{exact:true})).toBeVisible();
 await expect(dialog.getByText('new.csv',{exact:true})).toHaveCount(0);
 await expect(dialog.getByText('0test.csv',{exact:true})).toBeVisible();
 await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await expect(uploadButton).toBeFocused();await expect(page.getByRole('heading',{name:'new.csv',exact:true})).toBeVisible();
 await uploadButton.click();await dialog.locator('input[type=file]').setInputFiles({name:'new.csv',mimeType:'text/csv',buffer:Buffer.from('duplicate')});
 await dialog.locator('input[type=file]').setInputFiles({name:'new.csv',mimeType:'text/csv',buffer:Buffer.from('duplicate')});
 await expect(dialog.getByRole('alert')).toContainText('different filename');
 await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);
 await page.screenshot({path:output+'/desktop.png',fullPage:true});
 const before=(await (await page.request.get(base+'/api/documents')).json()).documents;
 const original=before.find(d=>d.name==='0test.csv');
 assert.equal((await page.request.get(base+'/api/documents/'+original.id+'/download')).status(),200);
 await page.getByRole('button',{name:'Delete new.csv',exact:true}).click();
 await expect(page.getByRole('heading',{name:'new.csv',exact:true})).toHaveCount(0);await expect(page.getByRole('status')).toContainText('Document deleted');
 await arrange(page,{action:'unavailable',value:true});await page.getByRole('button',{name:'Refresh',exact:true}).click();
 await expect(page.getByRole('alert')).toContainText('temporarily unavailable');await expect(page.getByRole('heading',{name:'No documents yet'})).toHaveCount(0);
 await arrange(page,{action:'unavailable',value:false});await page.getByRole('button',{name:'Retry',exact:true}).click();await expect(page.getByRole('alert')).toHaveCount(0);
 await arrange(page,{action:'remove',name:'0/0test.csv'});await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.getByRole('heading',{name:'No documents yet'})).toBeVisible();
 // Mobile uses the same real API, plus long-name and upload-modal checks.
 const mobileContext=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,acceptDownloads:true});
 await mobileContext.addCookies(await context.cookies());page=await mobileContext.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://consent.cookiebot.com/**',r=>r.abort());await page.goto(base+'/documents');
 await expect(page.getByRole('heading',{name:'No documents yet'})).toBeVisible();
 uploadButton=page.getByRole('button',{name:'Upload document',exact:true});dialog=page.getByRole('dialog',{name:'Upload documents'});
 await page.screenshot({path:output+'/empty-mobile.png',fullPage:true});
 await arrange(page,{action:'add',name:'0/A deliberately long customer contract filename with spaces.csv'});
 await page.getByRole('button',{name:'Refresh',exact:true}).click();
 await expect(page.getByRole('heading',{name:/deliberately long customer/})).toBeVisible();
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 const box=await page.getByRole('button',{name:/Download A deliberately/}).boundingBox();assert.ok(box.width>=44&&box.height>=44);
 await page.screenshot({path:output+'/mobile.png',fullPage:true});
 await uploadButton.click();await dialog.locator('input[type=file]').setInputFiles({name:'mobile.docx',mimeType:'application/octet-stream',buffer:Buffer.from('mobile')});
 const modalBox=await page.locator('.documents-page__modal').boundingBox();assert.ok(modalBox.x>=0&&modalBox.x+modalBox.width<=390);
 await page.screenshot({path:output+'/upload-mobile.png',fullPage:true});
 await dialog.getByRole('button',{name:'Upload',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.getByRole('heading',{name:'mobile.docx',exact:true})).toBeVisible();
 await page.request.post(base+'/api/logout',{headers:{'X-Requested-With':'camOS'}});await signIn(page,1);await page.goto(base+'/documents');
 await expect(page.getByRole('heading',{name:'private.csv',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'mobile.docx',exact:true})).toHaveCount(0);
 assert.equal((await page.request.get(base+'/api/documents/'+original.id+'/download')).status(),404);
 assert.deepEqual(errors,[]);
 console.log('PASS Documents real API/session + isolated objects: no login listing, empty/loading, admin refresh, flat ownership, download bytes, partial upload/duplicate protection, delete, outage recovery, mobile/focus/touch targets and two-user isolation.');
}finally{await browser?.close();runtime.kill('SIGTERM');}
